#!/bin/bash
_miuchiz()
{
    if [ "${#COMP_WORDS[@]}" == "2" ]; then
        compopt +o default
        COMPREPLY=($(compgen -W "dump-flash eject load-flash read-creditz set-creditz status" "${COMP_WORDS[1]}"))
    else
        compopt -o default
        COMPREPLY=()
        return 0
    fi
}

complete -F _miuchiz miuchiz